### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by unkby** [AlexKrutoy/CEX.IO-bot#10]
1. Стала появляться ошибка как на скриншоте
![2024-08-05_21-50-37](https://github.com/user-attachments/assets/ccb8c6a0-4ebb-478c-9f6f-f404575838a1)
3. Я внес правки,  чтобы была случайная задержка от 70 до 360 секунд, иначе сервер блокирует множество одновременных запросов
Строки 347-350 в файле CEX.IO-bot-main\bot\core\tapper.py
```
if (statuses is not None and all(statuses)) or only_check:

random_time = randrange(70, 360)

logger.success(f'{self.session_name} | Waiting before claiming, {random_time} s')

await asyncio.sleep(delay=random_time)


```

И строка 18 изменена:
`from random import shuffle, randint, randrange`

Можно исправить ошибку каким либо образом?

**Comment by parafius** [comment]
пофиксите админы пж
