### ISSUE TITLE
Unknown error when getting data, 429, message='Too Many Requests', url=URL('https://cexp.cex.io/api/getUserInfo')

### ISSUE THREAD

**Issue by Rollagit** [AlexKrutoy/CEX.IO-bot#2]
Unknown error when getting data, 429, message='Too Many Requests', url=URL('https://cexp.cex.io/api/getUserInfo')

how resolve this erorr ?
also not working in proxy mode

**Comment by mrdarkerr** [comment]
same

**Comment by itcthienkhiem** [comment]
same issue
