### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by mrdarkerr** [AlexKrutoy/CEX.IO-bot#5]
CEX.IO-bot | 2024-06-17 10:48:47 | ERROR    | 247 - n1 | Unknown error when starting farm, 429, message='Too Many Requests', url=URL('https://cexp.cex.io/api/startFarm')
CEX.IO-bot | 2024-06-17 10:48:47 | ERROR    | 409 - 913 | Unknown error: 'ClientResponseError' object is not subscriptable
CEX.IO-bot | 2024-06-17 10:48:47 | ERROR    | 247 - hiv | Unknown error when starting farm, 429, message='Too Many Requests', url=URL('https://cexp.cex.io/api/startFarm')
CEX.IO-bot | 2024-06-17 10:48:47 | ERROR    | 247 - god_of_nigga | Unknown error when starting farm, 429, message='Too Many Requests', url=URL('https://cexp.cex.io/api/startFarm')

**Comment by WubbaLubbaDubDubDev** [comment]
Same

**Comment by AlexKrutoy** [comment]
use proxy
